onlyflans/onlyflans/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('web/', include('web.urls')),
]

onlyflans/web/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import index, acerca, bienvenido, contacto, exito, registro, buscaflanes

app_name = 'web'

urlpatterns = [
    # example: /web/
    path('', index, name = 'índice'),
    # example: /web/acerca/
    path('acerca', acerca, name = 'acerca'),
    # example: /web/bienvenido/
    path('bienvenido', bienvenido, name = 'bienvenida'),
    # example: /web/contacto/
    path('contacto', contacto, name = 'contáctanos'),
    # example: /web/exito/
    path('exito', exito, name = 'éxito'),
    # example: /web/registro/
    path('registrar', registro, name = 'regístrate'),
    # example: /web/accounts/login/
    path('accounts/login', auth_views.LoginView.as_view(template_name = 'web/registration/login.html'), name = 'login'),
    # example: /web/accounts/logout/
    path('accounts/logout', auth_views.LogoutView.as_view(template_name = 'web/registration/logged_out.html'), name = 'logout'),
    # example: /web/buscaflan/
    path('buscaflan', buscaflanes, name = 'búscalo')
]

onlyflans/web/models.py
import uuid

from django.db import models


class Flan(models.Model):
    flan_uuid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    name = models.CharField(max_length = 64)
    description = models.TextField()
    image_url = models.URLField()
    slug = models.SlugField(max_length = 50, allow_unicode = True)
    is_private = models.BooleanField()


class ContactForm(models.Model):
    contact_form_uuid = models.UUIDField(primary_key = True, default = uuid.uuid4, editable = False)
    customer_email = models.EmailField(max_length = 150)
    customer_name = models.CharField(max_length = 64)
    message = models.TextField()

onlyflans/web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import ContactForm


class ContactFormForm(forms.Form):
    customer_email = forms.EmailField(label = 'Correo')
    customer_name = forms.CharField(max_length = 64, label = 'Nombre')
    message = forms.CharField(widget = forms.TextInput(attrs={'class': 'mensaje'}), label = 'Mensaje')


class ContactFormModelForm(forms.ModelForm):
    message = forms.CharField(widget = forms.Textarea(attrs={'rows': '4', 'cols': '30', 'style': 'resize: none;'}))
    
    class Meta:
        model = ContactForm
        fields = ['customer_name', 'customer_email', 'message']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label = "Correo electrónico")
    username = forms.CharField(label = "Nombre de usuario")
    password1 = forms.CharField(label = "Contraseña", widget = forms.PasswordInput)
    password2 = forms.CharField(label = "Confirmar contraseña", widget = forms.PasswordInput)

    class Meta:
            model = User
            fields = ['username', 'email', 'password1', 'password2']
            help_text = {k:"" for k in fields }

onlyflans/web/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages

from .models import ContactForm, Flan
from .forms import ContactFormForm, ContactFormModelForm, UserRegisterForm


def index(request):
    public_flans = Flan.objects.filter(is_private = False)
    return render(request, './web/index.html', {'public_flans': public_flans})

def acerca(request):
    return render(request, './web/about.html', {})

@login_required
def bienvenido(request):
    private_flans = Flan.objects.filter(is_private = True)
    return render(request, './web/welcome.html', {'private_flans': private_flans})

def contacto(request):
    if request.method == 'POST':
        form = ContactFormModelForm(request.POST)
        if form.is_valid():
            contact = ContactForm.objects.create(**form.cleaned_data)
            return HttpResponseRedirect('/web/exito')
    else:
        form = ContactFormModelForm()
    return render(request, './web/contact.html', {'form': form})

def exito(request):
    return render(request, './web/success.html', {})

def registro(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            # El método '.save()' permite guardar en la BD el registro de la variable 'form'
            form.save()
            # Se inicia la sesión  del usuario inmediatemente después del registro.
            usuario = form.cleaned_data['username']
            contrasena = form.cleaned_data['password1']
            new_user = authenticate(username = usuario, password = contrasena)
            login(request, user = new_user)
            # Se agrega un mensaje de éxito.
            messages.success(request, f'Usuario {usuario} registrado exitosamente.')
            # Redirección a la página de inicio
            return HttpResponseRedirect('/web/')
    else:
        form = UserRegisterForm()
    return render(request, './web/register.html', {'form': form})

def buscaflanes(request):
    if request.method == 'POST':
        # 'buscador' guarda el valor ingresado en el formulario de búsqueda.
        buscador = request.POST['buscador']
        # Filtrar los distintos objetos flanes para que coincidan con nuestro
        # criterio de búsqueda. En este caso, con el nombre de cada flan.
        flanes = Flan.objects.filter(name__contains = buscador)
        return render(request, './web/results_flans.html', {
            'buscador': buscador,
            'flanes': flanes,
            })
        
    else:
        return render(request, './web/results_flans.html', {})
    
    

onlyflans/web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--Etiqueta necesaria para la responsividad.-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--Link para habilitar la hoja de estilos CSS de Bootstrap v5.1.3, minificado, por CDN.-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!--Link para habilitar las fuentes de Google Fonts.-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!--URL de la fuente específica que se necesita.-->
    <link href="#" rel="stylesheet">
    <!--Link para habilitar los íconos de Font Awesome Free v6.0.0, por CDN.-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"
        integrity="sha384-3B6NwesSXE7YJlcLI9RpRqGf2p/EgVH8BgoKTaUrmKNDkHPStTQ3EyoYjCGXaOTS"
        crossorigin="anonymous">
    <!--Link para referenciar la hoja de estilos CSS local.-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Etiquetas para el title de la pestaña y el favicon.-->
    <title>Bienvenido a onlyFlans</title>
    <link rel="shortcut icon" type="#" href="#">
    <!--<meta> informativos para que tu página sea fácil de encontrar por los buscadores.-->
    <meta name="author" content="#">
    <meta name="description" content="#">
    <meta name="keywords" content="#">

</head>

<body>

    {% block 'header' %}
    {% include 'header.html' %}
    {% endblock %}

    {% block 'navbar' %}
    {% include 'navbar.html' %}
    {% endblock %}

    {% block 'contenido' %}
    <div class="container">
        <p>contenido</p>
    </div>
    {% endblock %}
    
    {% block 'footer' %}
    {% include 'footer.html' %}
    {% endblock %}

    <!--Link para habilitar el script JS de JQuery v3.6.0, minificado y con Ajax y módulos effects, por CDN.-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--Link para habilitar el script JS de Bootstrap v5.1.3, minificado y con Popper, por CDN.-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!--Link para habilitar archivos SVG de Font Awesome Free v6.0.0, por CDN.-->
    <script defer src="https://use.fontawesome.com/releases/v6.0.0/js/all.js"
        integrity="sha384-l+HksIGR+lyuyBo1+1zCBSRt6v4yklWu7RbG0Cv+jDLDD9WFcEIwZLHioVB4Wkau"
        crossorigin="anonymous"></script>
    <!--Link para referenciar el script JS local.-->
    <script src="#"></script>

</body>

</html>

onlyflans/web/templates/navbar.html
<nav class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'indice' %}">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'bienvenida' %}">Bienvenido</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'acerca' %}">Acerca</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</nav>

onlyflans/web/templates/web/about.html
{% extends 'web/base.html' %}

{% block 'contenido' %}
<div class="container p-5">
    <p class="my-4 fs-3">Acerca de OnlyFlans...</p>
    <p class="my-4 text-justify fs-5" id="lorem">Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis impedit ad distinctio culpa sequi nihil est aut esse. Obcaecati saepe, pariatur iusto eligendi maxime accusamus facilis soluta doloribus quia quo, corporis, quod architecto sint earum quidem accusantium quam rerum minima dicta maiores adipisci dolorum consequuntur sit? Eos, deleniti debitis. Qui.</p>
    <p class="my-4 text-justify fs-5" id="lorem">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias eum reprehenderit, nisi et saepe at aliquid maxime earum accusantium nihil nostrum explicabo optio vero ab expedita unde a dolores culpa aliquam, fugit quod omnis! Iure corrupti exercitationem maxime, ex eligendi fuga iusto. Molestiae laborum iure dolore provident, architecto consequuntur incidunt voluptatum eius cumque consectetur porro. Quas nam, dicta officia magnam totam non!</p>
    <br>
    <p class="my-4 text-justify fs-5" id="lorem">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat sapiente odio placeat facere rem aut dicta voluptate tempore, harum fugit. Voluptatem perspiciatis sed perferendis architecto.</p>
</div>
{% endblock 'contenido' %}

onlyflans/web/templates/web/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es" dir="ltr">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!--Etiqueta necesaria para la responsividad.-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!--Link para habilitar la hoja de estilos CSS de Bootstrap v5.1.3, minificado, por CDN.-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        crossorigin="anonymous">
    <!--Link para habilitar las fuentes de Google Fonts.-->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <!--URL de la fuente específica que se necesita.-->
    <link href="https://fonts.googleapis.com/css2?family=Pinyon+Script&family=Roboto:wght@400;500&display=swap"
    rel="stylesheet">
    <!--Link para habilitar los íconos de Font Awesome Free v6.0.0, por CDN.-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"
        integrity="sha384-3B6NwesSXE7YJlcLI9RpRqGf2p/EgVH8BgoKTaUrmKNDkHPStTQ3EyoYjCGXaOTS"
        crossorigin="anonymous">
    <!--Link para referenciar la hoja de estilos CSS local.-->
    <link rel="stylesheet" href="{% static './web/css/style.css' %}">
    <!--Etiquetas para el title de la pestaña y el favicon.-->
    <title>Bienvenido a OnlyFlans</title>
    <link rel="shortcut icon" type="#" href="{% static './web/img/favicon-black.png' %}">
    <!--<meta> informativos para que tu página sea fácil de encontrar por los buscadores.-->
    <meta name="author" content="#">
    <meta name="description" content="#">
    <meta name="keywords" content="#">

</head>

<body>

    {% block 'header' %}
    {% include 'web/header.html' %}
    {% endblock %}

    {% block 'navbar' %}
    {% include 'web/navbar.html' %}
    {% endblock %}

    {% block 'contenido' %}
    <div class="container">
        <p id="cont-text">contenido</p>
    </div>
    {% endblock %}
    
    {% block 'footer' %}
    {% include 'web/footer.html' %}
    {% endblock %}

    <!--Link para habilitar el script JS de JQuery 3.6.0, completo y minificado-->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!--Link para habilitar el script JS de Bootstrap v5.1.3, minificado y con Popper, por CDN.-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
    <!--Link para habilitar archivos SVG de Font Awesome Free v6.0.0, por CDN.-->
    <script defer src="https://use.fontawesome.com/releases/v6.0.0/js/all.js"
        integrity="sha384-l+HksIGR+lyuyBo1+1zCBSRt6v4yklWu7RbG0Cv+jDLDD9WFcEIwZLHioVB4Wkau"
        crossorigin="anonymous"></script>
    <!--Link para referenciar el script JS local-->
    <script src="{% static './web/js/script.js' %}"></script>

</body>

</html>

onlyflans/web/templates/web/contact.html
{% extends 'web/base.html' %}

{% block 'contenido' %}
<div class="container p-5">
    <p class="my-4 fs-3">Contacto.</p>

    <form action="contacto" method="post" class="text-center">
    {% csrf_token %}

        {{ form.non_field_errors }}
        <div class="mb-3 text-center">
            <label for="{{ form.customer_name.id_for_label }}" class="form-label success fs-5 mb-0">
                Nombre:
            </label>
            <div>
                {{ form.customer_name }}
            </div>
            <div id="error-form">
                {{ form.customer_name.errors }}
            </div>
        </div>
        <div class="mb-3 text-center">
            <label for="{{ form.customer_email.id_for_label }}" class="form-label success fs-5 mb-0">
                Correo electrónico:
            </label>
            <div>
                {{ form.customer_email }}
            </div>
            <div id="error-form">
                {{ form.customer_email.errors }}
            </div>
        </div>
        <div class="mb-3 text-center">
            <label for="{{ form.message.id_for_label }}" class="form-label success fs-5 mb-0">
                Ingresa tu consulta:
            </label>
            <div>
                {{ form.message }}
            </div>
            <div id="error-form">
                {{ form.message.errors }}
            </div>
        </div>
        <input type="submit" value="Enviar" class="btn boton-sesion my-3">
    </form>
</div>
{% endblock 'contenido' %}

onlyflans/web/templates/web/footer.html
<footer class="container py-2">
    <div class="text-center py-2">
        <p class="fs-4 my-auto">Co-Creado por Néstor Patricio & Miki - 2022</p>
    </div>
    <div class="row mx-2 mx-md-4 mx-xl-5 pb-2">
        <div class="d-inline-block col-6 mx-auto text-center display-6">
            <a href="https://www.linkedin.com/in/nestor-patricio-rojas-rios/"
                target="_blank" class="footer-ico mx-2" data-bs-toggle="tooltip"
                data-bs-placement="left" title="Néstor Patricio's LinkedIn">
                <i class="fa-brands fa-linkedin footer-ico"></i>
            </a>
            <a href="https://github.com/NestorPatricio"
                target="_blank" class="footer-ico mx-2" data-bs-toggle="tooltip"
                data-bs-placement="right" title="Néstor Patricio's GitHub">
                <i class="fa-brands fa-github-square footer-ico"></i>
            </a>
        </div>
        <div class="col-6 mx-auto text-center display-6">
            <a href="https://www.linkedin.com/in/nicole-elizabeth-manzo-salas-1b3233158/"
                target="_blank" class="footer-ico mx-2" data-bs-toggle="tooltip"
                data-bs-placement="left" title="Miki's LinkedIn">
                <i class="fa-brands fa-linkedin footer-ico"></i>
            </a>
            <a href="https://github.com/AoiMiki"
                target="_blank" class="footer-ico mx-2" data-bs-toggle="tooltip"
                data-bs-placement="right" title="Miki's GitHub">
                <i class="fa-brands fa-github-square footer-ico"></i>
            </a>
        </div>
    </div> 
</footer>

onlyflans/web/templates/web/header.html
{% load static %}
<header class="container">
    <div class="text-center">
        <img class = "img-fluid my-3" src="{% static './web/img/logo_onlyflans-white.png' %}" alt="OnlyFlans">
    </div>
</header>

onlyflans/web/templates/web/index.html
{% extends 'web/base.html' %}

{% block 'contenido' %}

<div class="container p-5">
    {% if messages %}
    {% for message in messages %}
    <div class="mb-4 fs-3 alert alert-dark {{message.tags}}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="shadow p-3 informacion rounded">
        <p class="mb-1 fs-3">Nuestros flanes</p>
        <p class="fs-6">Buscamos los secretos mejor guardados de  nuestras abuelas para entregarte los mejores flanes.</p>
        <a role="button" class="btn boton-sesion px-0 fs-5" href="{% url 'web:acerca' %}">Conócenos</a>
    </div>
    <div class="row">
        {% for flan in public_flans %}

        <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
            <div class="card shadow">
                <img src="{{ flan.image_url }}" class="img-fluid"
                    alt="Al rico flan">
                <div class="card-body">
                  <h5 class="card-title" id="hola">{{ flan.name }}</h5>
                  <p class="card-text">{{ flan.description }}</p>
                </div>
              </div>
        </div>

        {% endfor %}
    </div>
</div>

{% endblock 'contenido' %}

onlyflans/web/templates/web/navbar.html
<nav class="container">
    <div class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:índice' %}">Inicio</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:bienvenida' %}">Bienvenido</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:acerca' %}">Acerca</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'web:contáctanos' %}">Contacto</a>
                    </li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
            {% if not user.is_authenticated %}
                <a role="button" class="btn boton-sesion ms-auto" href="{% url 'web:login' %}">Inicia sesión</a>
                <a role="button" class="btn boton-sesion ms-3" href="{% url 'web:regístrate' %}">Regístrate</a>
            {% else %}
                <a role="button" class="btn boton-sesion ms-auto" href="{% url 'web:logout' %}">Cierra sesión</a>
            {% endif %}
            </div>
        </div>
    </div>
</nav>

onlyflans/web/templates/web/register.html
{% extends 'web/base.html' %}

{% block 'contenido' %}

<div class="container p-5">
    <p class="my-4 fs-3">Registro de usuarios.</p>
    <div class="row text-center">
        <div class="card col-12 col-md-6 col-lg-4 col-xl-3 mx-auto sin-borde">
            <div class="card-body">
                {% if not user.is_authenticated %}
                <form method="post" class="">
                {% csrf_token %}
                {{ form.as_p }}
                    <input type="submit" value="Regístrate" class="btn boton-sesion my-3">
                </form>
                {% else %}
                <div class="my-4 fs-3 alert alert-dark">
                    Ya eres un usuario registrado, {{ user.username }}.
                </div>
                {% endif %}
            </div>
        </div>

    </div>
</div>
    
{% endblock 'contenido' %}

onlyflans/web/templates/web/results_flans.html
{% extends 'web/base.html' %}

{% block 'contenido' %}
<div class="container p-5">

{% if not user.is_authenticated %}
    <h3>No tienes acceso a esta sección.</h3>
    <br>
    <a class="fs-6 logout" href="{% url 'web:login' %}">Si quieres ver más productos inicia tu sesión.</a>
{% else %}

    {% if buscador %}
    <p class="mt-4 mb-2 fs-3">Estos flanes coinciden con {{ buscador }}:</p>

    <div class="row">
        {% for flan in flanes %}
        <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
            <div class="card shadow">
                <img src="{{ flan.image_url }}" class="img-fluid"
                    alt="Al rico flan">
                <div class="card-body">
                  <h5 class="card-title" id="hola">{{ flan.name }}</h5>
                  <p class="card-text">{{ flan.description }}</p>
                </div>
              </div>
        </div> 
        {% endfor %}
    </div>
    {% else %}
    <p class="my-4 fs-3">No has realizado tu búsqueda aún.</p>
    {% endif %}

    {% block 'searcher' %}
    {% include 'web/search_flans.html' %}
    {% endblock %}

{% endif %}

</div>
{% endblock 'contenido' %}

onlyflans/web/templates/web/search_flans.html
<!-- Acá se crea el bloque HTML específico para el buscador. -->
<div class="mt-5 text">
    <p class="my-4 fs-3">Encuentra tu flan:</p>
    <form action="{% url 'web:búscalo' %}" method="post" clas="">
    {% csrf_token %}
        <div class="row ps-0 mx-0">
            <div class="ps-0 mb-3 mb-lg-0 col-12 col-lg-9 col-xl-10">
                <input class="me-4 form-control" type="search"
                placeholder="Encuentra tu flan..." aria-label="Encuentra tu flan"
                name="buscador">
            </div>
            <button class="btn boton-sesion ms-auto col-12 col-lg-3 col-xl-2" type="submit">Buscar</button>    
        </div>
    </form>
</div>

onlyflans/web/templates/web/success.html
{% extends 'web/base.html' %}

{% block 'contenido' %}
<div class="container p-5 succes text-center">
    <h3>¡Gracias por contactarte con OnlyFlans!</h3>
    <h3>Te responderemos a la brevedad.</h3>
    <a role="button" class="btn btn-primary boton-sesion mt-5" href="{% url 'web:índice' %}">Volver al inicio</a>
</div>
{% endblock 'contenido' %}

<div class="container p-5 text-center">
    <h3>Has cerrado tu sesión correctamente.</h3>
    <a class="fs-5 logout mx-3" href="{% url 'web:índice' %}">Vuelve al Inicio</a> |
    <a class="fs-5 logout mx-3" href="{% url 'web:login' %}">Reinicia tu sesión</a>
</div>

onlyflans/web/templates/web/welcome.html
{% extends 'web/base.html' %}

{% block 'contenido' %}
<div class="container p-5">
    <div class="shadow p-3 informacion rounded">
        <p class="mb-1 fs-3">Bienvenido {{ user.username }}</p>
        <p class="fs-6">Tenemos los más exclusivos productos para conquistar tu paladar ¿Quieres conocerlos?</p>
        <a role="button" class="btn boton-sesion px-0 fs-5" href="{% url 'web:contáctanos' %}">Contáctanos</a>
    </div>

    {% block 'searcher' %}
    {% include 'web/search_flans.html' %}
    {% endblock %}

    <div class="row">
        {% for flan in private_flans %}
        <div class="col-12 col-md-6 col-lg-4 col-xl-3 mt-5 mb-2">
            <div class="card shadow">
                <img src="{{ flan.image_url }}" class="img-fluid"
                    alt="Al rico flan">
                <div class="card-body">
                  <h5 class="card-title" id="hola">{{ flan.name }}</h5>
                  <p class="card-text">{{ flan.description }}</p>
                </div>
              </div>
        </div> 
        {% endfor %}
    </div>
</div>
{% endblock 'contenido' %}